import Head from "next/head";
import Styled from "styled-components";
import tw from "twin.macro";
import axios from "axios";

const AppContainer = Styled.div`
${tw`flex w-full h-full h-screen overflow-hidden bg-gray-400`}

`;
export default function Home() {
  return (
    <AppContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      iuifytc
    </AppContainer>
  );
}


