import Head from "next/head";
import Styled from "styled-components";
import tw from "twin.macro";
import ProductsList from "../components/products/productsList";
import { getProducts } from "../../services/products";

const AppContainer = Styled.div`
${tw`flex w-full h-full overflow-hidden bg-gray-400`}

`;
export default function Home({ products, messages }) {
  return (
    <AppContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductsList products={products} />
      {/* {JSON.stringify(products)} */}
    </AppContainer>
  );
}

export async function getStaticProps() {
  const { products, messages } = await getProducts();

  console.log(products);

  return {
    props: {
      products,
      messages,
    },
  };
}
